# Model Configuration
GOOSE_PROVIDER: "xai"
GOOSE_MODEL: "grok-4-latest"
GOOSE_TEMPERATURE: 0.7

# Planning Configuration
GOOSE_PLANNER_PROVIDER: "xai"
GOOSE_PLANNER_MODEL: "grok-4-latest"

# Tool Configuration
#Controls how Goose handles tool execution	"auto", "approve", "chat", "smart_approve"
GOOSE_MODE: "smart_approve"
GOOSE_TOOLSHIM: true
GOOSE_CLI_MIN_PRIORITY: 0.2

# Recipe Configuration
GOOSE_RECIPE_GITHUB_REPO: "block/goose-recipes"

GOOSE_CLI_SHOW_COST: true

# Experimental Features
ALPHA_FEATURES: true

